language: nix

sudo: true
arch:
  - amd64
  - ppc64le
git:
  depth: 1

env:
  global:
  matrix:
    - GHCVERSION=ghc802
    - GHCVERSION=ghc822
    - GHCVERSION=ghc843

matrix:
  allow_failures:
  exclude:

script:
  - (cd gitlib ; nix-build --argstr compiler $GHCVERSION)

branches:
  only:
    - master
